CREATE TABLE EMPRESA(
	ID_EMPRESA int not null,
     RAZON_SOCIAL varchar(60) NOT NULL,
     NIT_EMPRESA varchar(12) NOT NULL,
     DIR_EMPRESA varchar(80) NOT NULL,
     CORREO_EMPRESA varchar(90) NOT NULL,
     REPRESENTANTE varchar(90) NOT NULL,
     TELEFONO_EMPRESA varchar(12) NOT NULL,
    PRIMARY KEY (ID_EMPRESA)
); 

CREATE TABLE PAIS (
     ID_PAIS INT NOT NULL,
     NOMBRE_PAIS varchar(40) NOT NULL,
	 ESTADO_PAIS CHAR(1),
    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE DEPARTAMENTO (
     ID_DPTO INT NOT NULL,
     NOMBRE_DPTO varchar(40) NOT NULL,
     ID_PAIS_DPTO INT NOT NULL,
	 ESTADO_DPTO CHAR(1),
    PRIMARY KEY (ID_DPTO),
    FOREIGN KEY (ID_PAIS_DPTO) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE CIUDAD (
     ID_CIUDAD INT NOT NULL,
	 COD_CIUDAD VARCHAR(6) NOT NULL,
     NOMBRE_CIUDAD varchar(40) NOT NULL,
     ID_DPTO_CIUDAD INT NOT NULL,
	 ESTADO_CIUDAD CHAR(1),
    PRIMARY KEY (ID_CIUDAD),
    FOREIGN KEY (ID_DPTO_CIUDAD) REFERENCES DEPARTAMENTO(ID_DPTO)
);

CREATE TABLE TIPO_DOCUMENTO (
     ID_DOCUMENTO INT NOT NULL,
     NOMBRE_DOCUMENTO varchar(60) NOT NULL,
    PRIMARY KEY (ID_DOCUMENTO)
);

CREATE TABLE TIPO_CLIENTE (
     ID_TIPO_CLIENTE INT NOT NULL,
     DESCRIPCION_TCLIENTE VARCHAR(40) NOT NULL,
	 ESTADO_TCLIENTE CHAR(1),
    PRIMARY KEY (ID_TIPO_CLIENTE)
);


CREATE TABLE CLIENTE (
     ID_CLIENTE INT NOT NULL,
	 ID_EMPRESA INT NOT NULL,
	 NIT_CLIENTE VARCHAR(15) NOT NULL,
	 RSOCIAL_CLIENTE VARCHAR(70) NOT NULL,
	 ID_TIPO_CLIENTE FLOAT NOT NULL,
	 NOMBRE_CLIENTE VARCHAR(75) NOT NULL,
	 APELLIDO_CLIENTE VARCHAR(75) NOT NULL,
	 DIR_CLIENTE VARCHAR(85) NOT NULL,
	 ID_CIUDAD INT NOT NULL,
	 CORREO_CLIENTE VARCHAR(85) DEFAULT NULL,
	 TEL_CLIENTE VARCHAR(30) NOT NULL,
	 CODPOSTAL_CLIENTE VARCHAR(15),
	 CUPOCREDITO_CLIENTE INT DEFAULT 0,
	 SALDO_CLIENTE INT DEFAULT 0,
	 COMPRASMES_CLIENTE INT DEFAULT 0,
	 PAGOSMES_CLIENTE INT DEFAULT 0,
	 ESTADO_CLIENTE CHAR(1),
     PRIMARY KEY (ID_CLIENTE),
	 FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE PARAMETRO_GENERAL (
     ID_PARAMETRO_GENERAL INT NOT NULL,
     NOMBRE_PARAMETRO VARCHAR(10) NOT NULL,
     DESCRIPCION_PARAMETRO VARCHAR(60) NOT NULL,
     VALOR_PARAMETRO VARCHAR(100) NOT NULL,
     TIPO_PARAMETRO VARCHAR(1) NOT NULL,
    PRIMARY KEY (ID_PARAMETRO_GENERAL)
);

CREATE TABLE CATEGORIA (
     ID_CATEGORIA INT NOT NULL,
     NOM_CATEGORIA VARCHAR(35) NOT NULL,
	 ESTADO_CATEGORIA VARCHAR(1),
    PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PRODUCTO (
  ID_PRODUCTO INT NOT NULL,
  ID_CATEGORIA INT NOT NULL,
  COD_PRODUCTO VARCHAR(12) NOT NULL,
  DES_PRODUCTO VARCHAR(60) NOT NULL,
  EXIS_PRODUCTO INT DEFAULT 0,
  BODEGA_PRODUCTO INT DEFAULT 0,
  PRECIO_VENTA_ACT FLOAT DEFAULT 0,
  PRECIO_VENTA_ANT FLOAT DEFAULT 0,
  DSCTO_MINIMO INT DEFAULT 0,
  DSCTO_MAXIMO INT DEFAULT 0,
  COSTO_VENTA FLOAT DEFAULT 0,
  MARGEN_UTILIDAD FLOAT DEFAULT 0,
  VALOR_IVA FLOAT DEFAULT 0,
  STOCK_MINIMO INT DEFAULT 0,
  STOCK_MAXIMO INT DEFAULT 0,
  ESTADO_PRODUCTO VARCHAR(1) NOT NULL,
  PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE TIPOMOV (
     ID_TIPOMOV INT NOT NULL,
     NOM_TIPOMOV VARCHAR(45) NOT NULL,
	 ESTADO_TIPOMOV VARCHAR(1),
    PRIMARY KEY (ID_TIPOMOV)
);

INSERT INTO TIPOMOV VALUES(1,'Actualización de precios','A');
INSERT INTO TIPOMOV VALUES(2,'Ingreso por Compras','A');
INSERT INTO TIPOMOV VALUES(3,'Entrada por Ajuste','A');
INSERT INTO TIPOMOV VALUES(4,'Salida por Ajuste','A');
INSERT INTO TIPOMOV VALUES(5,'Ventas Crédito','A');
INSERT INTO TIPOMOV VALUES(6,'Ventas Contado','A');
INSERT INTO TIPOMOV VALUES(7,'Ingreso a Bodega','A');
INSERT INTO TIPOMOV VALUES(8,'Salida de Bodega','A');

CREATE TABLE MOVPRODUCTO (
     ID_MOV INT NOT NULL,
	 ID_TIPOMOV INT NOT NULL,
	 CANTIDAD_MOV INT DEFAULT 0,
	 ID_PRODUCTO INT NOT NULL,
	 FECHA_MOVIMIENTO DATE NOT NULL,
	 ESTADO_MOVIMIENTO VARCHAR(1),
    PRIMARY KEY (ID_MOV)
);

CREATE TABLE TIPOFACTURA (
     ID_TIPOFAC INT NOT NULL,
     NOM_TIPOFAC VARCHAR(45) NOT NULL,
	 ESTADO_TIPOFAC VARCHAR(1),
    PRIMARY KEY (ID_TIPOFAC)
);

CREATE TABLE FACTURA (
  ID_FACTURA INT NOT NULL,
  FECHA_FACTURA DATE NOT NULL,
  ID_TIPOFAC INT NOT NULL,
  CLIENTE_FACTURA INT NOT NULL,
  TOTAL_FACTURA FLOAT DEFAULT 0,
  DESCUENTO_FACTURA FLOAT DEFAULT 0,
  IVA_FACTURA FLOAT DEFAULT 0,
  SUBTOTAL_FACTURA FLOAT DEFAULT 0,
  SALDO_FACTURA FLOAT DEFAULT 0,
  ESTADO_FACTURA VARCHAR(1) NOT NULL,
  PRIMARY KEY (ID_FACTURA)
);

CREATE TABLE DETALLEFACTURA (
  ID_DETALLE_FACTURA INT NOT NULL,
  ID_FACTURA INT NOT NULL,
  ID_PRODUCTO INT NOT NULL,
  CANT_VENDIDA INT DEFAULT 0,
  PRECIO_VENTA FLOAT DEFAULT 0,
  VALOR_IVA FLOAT DEFAULT 0,
  DESCTO_DETFAC FLOAT DEFAULT 0,
  PRIMARY KEY (ID_DETALLE_FACTURA)
);

CREATE TABLE RECAUDO (
     ID_RECAUDO INT NOT NULL,
	 ID_CLIENTE_RECAUDO INT NOT NULL,
	 ID_FACTURA_RECAUDO INT NOT NULL,
	 VALOR_RECAUDO INT DEFAULT 0,
	 FECHA_RECAUDO date,
     PRIMARY KEY (ID_RECAUDO),
	 FOREIGN KEY (ID_CLIENTE_RECAUDO) REFERENCES CLIENTE(ID_CLIENTE),
	 FOREIGN KEY (ID_FACTURA_RECAUDO) REFERENCES FACTURA(ID_FACTURA)
);


